language: c # disable cabal

branches:
  only:
  - master

git:
  depth: 3

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
    - fpcomplete-trusty
    packages:
    - stack

install:
- stack --no-terminal --install-ghc install Agda

script:
- stack exec agda -- --library-file=libraries-travis theorems/index.agda
