language: c # disable cabal

branches:
  only:
  - master

git:
  depth: 3

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
    - fpcomplete-precise
    packages:
    - stack

install:
- travis_wait stack --no-terminal --install-ghc --resolver lts-8 install Agda

script:
- stack exec agda -- --version
# 2-stage type-checking to reduce peak memory usage, hopefully
- stack exec agda -- --library-file=libraries-travis --without-K --rewriting core/HoTT.agda
# checking this file is very demanding, so it is checked first (actually, I gave up on this)
# - stack exec agda -- --library-file=libraries-travis --without-K --rewriting theorems/homotopy/3x3/Commutes.agda
# checking the rest
- stack exec agda -- --library-file=libraries-travis --without-K --rewriting theorems/index.agda
