language: c # disable cabal

branches:
  only:
  - master

git:
  depth: 3

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
    - fpcomplete-precise
    packages:
    - stack

install:
- stack --no-terminal --install-ghc install Agda

script:
- stack exec agda -- --version
# 2-stage type-checking to reduce peak memory usage, hopefully
- stack exec agda -- --library-file=libraries-travis core/HoTT.agda
# this file is very demanding, so it is checked first
- stack exec agda -- --library-file=libraries-travis theorems/homotopy/3x3/Commutes.agda
# checking the rest
- stack exec agda -- --library-file=libraries-travis theorems/index.agda
